export const BOOK_STATUSES = ['TO_READ', 'READING', 'READ', 'PAUSED', 'ABANDONED'];
export const MOOD_TAGS = ['MOVED', 'CALM', 'JOYFUL', 'SAD', 'ANGRY', 'CONFUSED', 'RELIEVED', 'EMPTY', 'CHANGED'];
export const TRACE_TYPES = ['DOG_EAR', 'ANNOTATION', 'REREAD_MARK'];
export const ACTIVITY_ACTIONS = [
  'CREATED',
  'UPDATED',
  'DELETED',
  'RESTORED',
  'STATUS_CHANGED',
  'COMPLETED',
  'REVISION_RESTORED'
];
export const ACTIVITY_ENTITY_TYPES = ['BOOK', 'DOG_EAR', 'ANNOTATION', 'REREAD_MARK', 'COMPLETION_REFLECTION'];
export const REVISION_ACTIONS = ['INITIAL', 'UPDATED', 'DELETED', 'RESTORED', 'VERSION_RESTORED'];
